### PR TITLE
add builder route behind experiment

### PR DESCRIPTION
**Pull request by lmossman**
## What
Resolves https://github.com/airbytehq/airbyte/issues/21284

Enables the /connector-builder route on cloud behind a feature flag, reusing the `connectorBuilder.showNavigationLinks` experiment that controls if connector builder navigation links are shown.

This is being done in preparation for adding the connector builder server to cloud, to allow the connector builder UI to be opened in cloud for testing that addition.

## How
There are two ways to test this out:
1. Using the local `.experiments.json` file:
    - Create file at `airbyte-platform/airbyte-webapp/.experiments.json` with the contents
      ```
      {
        "connectorBuilder.showNavigationLinks": true
      }
      ```
    - Run `pnpm run start:cloud`
    - Click on the Builder button in the sidebar to open the connector builder route.
2. Using LaunchDarkly
    - Remove the `.experiments.json` value if you already enabled the experiment there
    - Run `pnpm run start:cloud`
    - Go to https://app.launchdarkly.com/, and log in with the dev-frontend@airbyte.io LaunchDarkly credentials from LastPass
    - Navigate to https://app.launchdarkly.com/default/test/features/connectorBuilder.showNavigationLinks/targeting, and add yourself as an individual target for the `true` value
    - The Builder navigation links should now show up in the webapp, use them to open the connector builder

The connector builder will actually work properly if you have a locally running OSS instance, because it makes requests to `localhost:3003` when calling the connector builder server. But when this is actually deployed to a dev environment or prod, the connector builder server calls will fail because there is not currently a connector builder server container running in cloud deployments. (I tried testing this out but failed to deploy this branch to cloud: https://github.com/airbytehq/airbyte-platform-internal/actions/runs/4288573761/jobs/7470749347, asked about this on slack [here](https://airbytehq-team.slack.com/archives/C046KQF5GBT/p1677548958003739))

## 🚨 User Impact 🚨
No user impact since this is hidden behind a feature flag.

### CODE REVIEW

**Review by flash1293 — APPROVED** [review]
Tested in both configurations and works as expected, LGTM.

**Comment by lmossman** [comment]
Closing in favor of https://github.com/airbytehq/airbyte-platform-internal/pull/4807

**Pull request closed without merging**
