### PR TITLE
🪟 🧹 Remove Sentry from Webapp

### PR DESCRIPTION
**Pull request by tealjulia**
## What
closes https://github.com/airbytehq/airbyte/issues/21700

Removes all remaining code for Sentry tracking in the FE code.  We had already migrated all error tracking to DataDog; this removes the rest of the Sentry-related code.

## How
^ doing that

## Recommended reading order
any

## Can this PR be safely reverted / rolled back?
*If you know that your PR is backwards-compatible and can be simply reverted or rolled back, check the YES box.*

*Otherwise if your PR has a breaking change, like a database migration for example, check the NO box.*

*If unsure, leave it blank.*
- [X] YES 💚
- [ ] NO ❌

## 🚨 User Impact 🚨
None.  This is removing unused configuration code for Sentry (all tracking had already been migrated to DataDog).  Users will not be impacted.

### CODE REVIEW

**Review by timroes — APPROVED** [review]
Code LGTM. Have not tested locally. Can you also make sure to remove the code from airbyte-platform-internal that currently sets different SENTRY URLS in there?

**Review by josephkmh — APPROVED** [review]
Nice! Tested locally and everything looked good.

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
