### PR TITLE
Updated template to fix metrics helm issue

### PR DESCRIPTION
**Pull request by talha-naeem1**
**What:**

While deploying airbyte metrics helm chart, I had to pass imagepullsection in values file like this:
```
global:
  imagePullSecrets:
    - name: "ghcr-secret"
 ```

While i was installing helm chart i was getting this issue:
```
Error: YAML parse error on airbyte/charts/metrics/templates/deployment.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 25: did not find expected key
YAML parse error on airbyte/charts/metrics/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:304
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:306
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:95
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1598
```

**How:**

I have fixed the identation which is causing the above mentioned error and blcoks the usage of airbyte-platform helm chart with any custom image.

### CODE REVIEW

**Comment by talha-naeem1** [comment]
Fixes https://github.com/airbytehq/airbyte/issues/42932

**Comment by marcosmarxm** [comment]
Thanks for the contribution @talha-naeem1 I'm going to ask the deployment team to take a look

**Comment by perangel** [comment]
This has been merged, thank you for the contribution!

**Pull request closed without merging**
