### PR TITLE
Fix DATABASE_PASSWORD env for airbyte-metrics helm chart

### PR DESCRIPTION
**Pull request by octavia-squidington-iii**
## What
Resolves https://github.com/airbytehq/airbyte/issues/23226

Currently the airbyte-metrics pod does not start up due to being unable to find the env. More info in the issue linked above, but I was able to get it to start normally with the change included in this PR.

Maybe this change was meant to be included in https://github.com/airbytehq/airbyte/pull/16131?

## How
This PR brings the airbyte-metrics deployment.yaml template in conformance with other charts pulling this secret.

a couple examples of the pattern used elsewhere that I've copied:

https://github.com/airbytehq/airbyte-platform/blob/15a34b8af95e9dbaf4c07980b3f09d724072dc8b/charts/airbyte-server/templates/deployment.yaml#L77-L81

https://github.com/airbytehq/airbyte-platform/blob/15a34b8af95e9dbaf4c07980b3f09d724072dc8b/charts/airbyte-temporal/templates/deployment.yaml#L72-L76

source: https://github.com/airbytehq/airbyte/pull/23230

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
@xpuska513 since you have added this change to other templates, I would appreciate your input and review 🙏🏽

source: https://github.com/airbytehq/airbyte/pull/23230#issuecomment-1435369349

**Comment by sh4sh** [comment]
Also @davinchia would appreciate your review!

**Comment by davinchia** [comment]
Thanks @sh4sh ! This looks right to me.

I also want @xpuska513 to double check before we merge this in.

**Review by xpuska513 — APPROVED** [review]
Looks good to me, AC tests passed so I think we can merge this in

**Pull request merged**
