### PR TITLE
Upgrade temporal to latest release

### PR DESCRIPTION
**Pull request by vr**
This is the following of https://github.com/airbytehq/airbyte/pull/21978 @marcosmarxm 

Best will be to upgrade to latest temporal release, but at least bump to latest v1.13.x to get rid of the CVE.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @vr for the update. @davinchia / @benmoriceau is it possible to take a look and execute some tests?

**Comment by vr** [comment]
BTW the image is vulnerable by itself because it has been built a long time ago, i think we really need to update it on a more regular schedule.
image
image

**Comment by davinchia** [comment]
@vr thanks! we ware working through some of our tooling now. I will get this merged in once that is done, probably at the start of next week.

**Comment by vr** [comment]
Looking at the 1.13.4 Dockerfile this will not fix all the CVE because it depends on a version of docker.io/temporalio/base-server which is one year old.

It looks like the goal of rebuilding our own base for temporal image is useless now because they now build arm64 image so we can just use their base image, it will be way simpler for security upgrade.

I updated my commit.

I tried to test it but i can't get the test script working, can you check it maybe ?

**Comment by vr** [comment]
any updates on this ?

**Comment by davinchia** [comment]
This is failing internal tests. There was a fire on my street last week which took out the internet so I haven't had a chance to look at this yet. Will update you.

**Comment by vr** [comment]
any updates here @davinchia ?

**Comment by vrfn** [comment]
Hi @davinchia, would be great if this gets merged as the version that is currently used is ancient 😄

**Comment by marcosmarxm** [comment]
@vr and @vrfn there were some attempts to upgrade temporal to latest version but it wasn't possible. 
@pmossman do you have information to share about this?

**Comment by imonacloud** [comment]
any updates here? this is an issue for airbyte users deploying with helm charts + terraform where temporal v1.13.0 (which we use now) can't handle temporal and temporal_visibility dbs being pre-created but v1.15.0 of temporal can

**Comment by flutra-osmani** [comment]
This change was merged; closing the ticket.

**Pull request closed without merging**
