### PR TITLE
Refactor Source Item Page to match Destination Item Page, don't load source twice

### PR DESCRIPTION
**Pull request by timroes**
Migration of https://github.com/airbytehq/airbyte/pull/23002

## What
Resolves https://github.com/airbytehq/airbyte/issues/21663
Converts the source item page to be more like destination item page.

## How
The source item page had its routes defined in the page instead of in the routes. I've pulled the routes up and now use outlet to render the appropriate page. Additionally I've leveraged the outlet context so we aren't loading the source on both pages.

### CODE REVIEW

**Review by octavia-squidington-iii — APPROVED** [review]
Less requests > more requests. Approving since Edmundo and Vlad already approved the original PR.

**Comment by pmossman** [comment]
@timroes and @krishnaglick looks like this PR now has merge conflicts, can you look into resolving when you get a chance? I will skip this PR for today's daily deploy

**Comment by krishnaglick** [comment]
@pmossman "Conflicts" resolved. Nothing required my input but git flagged it as a conflict. Oh well! Good to go today :)

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
