### PR TITLE
🪟 🎨 Add selected field count to new streams table

### PR DESCRIPTION
**Pull request by dizel852**
## What
Resolves https://github.com/airbytehq/airbyte/issues/21772

## How
Adds fields count: {selected} / {total} to the new streams table

Screenshot at Feb 28 23-35-42

### CODE REVIEW

**Comment by krishnaglick** [comment]
You may need to rebase this on `main`. The diff is wild

**Comment by dizel852** [comment]
> You may need to rebase this on `main`. The diff is wild

Yeah, def need, didn't notice so many changes, thanks!

**Comment by krishnaglick** [comment]
> > You may need to rebase this on `main`. The diff is wild
> 
> Yeah, def need, didn't notice so many changes, thanks!

You may need to move this to `-internal` to fix the diff unfortunately.

**Comment by dizel852** [comment]
> > > You may need to rebase this on `main`. The diff is wild
> > 
> > 
> > Yeah, def need, didn't notice so many changes, thanks!
> 
> You may need to move this to `-internal` to fix the diff unfortunately.

Will do 👌

**Comment by dizel852** [comment]
Closing, since it was migrated https://github.com/airbytehq/airbyte-platform-internal/pull/4802

**Pull request closed without merging**
