### PR TITLE
Pass otel collector endpoint env var to orchestrator

### PR DESCRIPTION
**Pull request by kostiantyn-nemchenko**
## What
`OTEL_COLLECTOR_ENDPOINT` is not passed into the orchestrator pod resulting in sync failures when `METRIC_CLIENT` is set to `otel`. Please, see [#22401](https://github.com/airbytehq/airbyte/issues/22401) for details.

## How
Injected missing environment variable.

### CODE REVIEW

**Comment by justenwalker** [comment]
@xiaohansong may want to take a look at this.  
IMO looks fairly straight-forward; passing the missing env down to orchestrator pods.

**Review by xiaohansong — APPROVED** [review]

**Comment by kostiantyn-nemchenko** [comment]
@xiaohansong @perangel Do I need to do anything else for this PR to be merged?

**Comment by xiaohansong** [comment]
merged. thanks!

**Pull request closed without merging**
