### PR TITLE
Allow to specify init job timeout

### PR DESCRIPTION
**Pull request by AKuzyashin**
## What
Current timeout of 5 minutes is to low for aws spot instances 
## How
Allow change timeout 

## Can this PR be safely reverted / rolled back?
*If you know that your PR is backwards-compatible and can be simply reverted or rolled back, check the YES box.*

*Otherwise if your PR has a breaking change, like a database migration for example, check the NO box.*

*If unsure, leave it blank.*
- [x] YES 💚
- [ ] NO ❌

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

### CODE REVIEW

**Review by Barsoomx — APPROVED** [review]
lgtm! very useful tweak for k8s

**Comment by Barsoomx** [comment]
@cpdeethree can you please take a look?

**Comment by cpdeethree** [comment]
Hello!

Thank you for your contribution!

We think allowing this to be configurable makes a ton of sense! We are not currently thinking it is a good idea to set the default to 5 minutes, however. We think it does absolutely make sense in your case though, since spot instances can take a long time to spin up. Could we revert that specific change back to 1 minute? After doing that, we are happy to accept your change!

**Review by cpdeethree — APPROVED** [review]

**Pull request closed without merging**
