### PR TITLE
Update to Micronaut 3.8.5

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Stay up to date with framework improvements and fixes
* https://github.com/micronaut-projects/micronaut-core/releases/tag/v3.8.4
* https://github.com/micronaut-projects/micronaut-core/releases/tag/v3.8.5
* Copy of https://github.com/airbytehq/airbyte/pull/22560

## How
* Bump Micronaut and related dependencies to latest release

## Recommended reading order
1. `deps.toml`

## Can this PR be safely reverted / rolled back?
- [X] YES 💚
- [ ] NO ❌

## 🚨 User Impact 🚨
None

### CODE REVIEW

**Review by cgardens — APPROVED** [review]

**Review by colesnodgrass — APPROVED** [review]

**Comment by benmoriceau** [comment]
LGTM, I think that we should do the same for airbyte/airbyte

**Review by benmoriceau — APPROVED** [review]
One comment for airbyte/airbyte

**Comment by octavia-approvington** [comment]
A crack team of mammals has made a decision.  <br/> imagine a seal of approval

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
