### PR TITLE
Turn on slack notifications

### PR DESCRIPTION
**Pull request by alovew**
Turn on Slack Notifications for Schema Changes that are detected automatically

### CODE REVIEW

**Comment by gosusnp** [comment]
@alovew, what's the impact of this change? are we turning it on for the first time in prod or just changing the default?

**Comment by alovew** [comment]
@gosusnp turning it on for the first time in prod

**Comment by gosusnp** [comment]
> turning it on for the first time in prod

In this case, I think we should update the value set in the charts, not the default. I don't think I review all the pieces related to this change, does this flag only control the addition of a new workflow or will we start notifying users for all changes?
I think we still have some latent schema change issues, https://github.com/airbytehq/oncall/issues/1515 has been added to the backlog, are we going to start notifying those connections?

**Comment by alovew** [comment]
This only controls the workflow - the default is set to true since that's how the other temporal workflow are set. Users can still have the option to turn on or off notifications for their particular connections.

**Review by benmoriceau — APPROVED** [review]

**Review by gosusnp — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
