### PR TITLE
Issue #23679 - Allow for increased timeouts for check connections

### PR DESCRIPTION
**Pull request by abhishekbiyala**
## What
Fix for https://github.com/airbytehq/airbyte/issues/23679
Github source check connection times out when connecting with organization that has large number of repositories.  This fix allows for increase in airbyte-worker, airbyte-server and airbyte-proxy layers.

## How
This change is to allow increased timeout at 3 places:
1. Made `checkActivityOptions` timeout configurable in airbyte-worker. The default value remains unchanged at 5m
2. Made `micronaut.server.idle-timeout` configurable in airbyte-server. The default value remains unchanged at 5m
3. Increased `BASIC_AUTH_PROXY_TIMEOUT` from 600 to 900 in .env file since this is used at build time of airbyte-proxy

## Recommended reading order
1. `ActivityBeanFactory.java`
2. `airbyte-workers/src/main/resources/application.yml`
3. `airbyte-server/src/main/resources/application.yml`
4. `.env`
5. `airbyte-proxy/build.gradle`

## Can this PR be safely reverted / rolled back?
*If you know that your PR is backwards-compatible and can be simply reverted or rolled back, check the YES box.*

*Otherwise if your PR has a breaking change, like a database migration for example, check the NO box.*

*If unsure, leave it blank.*
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@pmossman can you take a look on this community contribution?

**Review by pmossman — APPROVED** [review]
Looks reasonable to me!

**Comment by pmossman** [comment]
I'm going to open an internal PR with this branch to run our CI suite and see if it all passes

**Comment by pmossman** [comment]
@abhishekbiyala I merged your PR into our internal repository, it will be reflected to the airbytehq/airbyte-platform repository soon! Thanks for the contribution, and sorry this took so long, it fell off my radar due to some misconfigured stale PR reminders on my end 😬

**Pull request closed without merging**
