### PR TITLE
API to complete OAuth and return secret

### PR DESCRIPTION
**Pull request by octavia-squidington-iii**
## What
New endpoint which extends the current complete_oauth endpoint to allow returning secret IDs from GSM for token data.

We're doing this work to enable usage of the current oauth flow via the API for the Powered by Airbyte headless use case. This also has the added benefit of opening up the option for the frontend to use these endpoints 

See [this doc](https://docs.google.com/document/d/1bwN-w_w5Fn6ILjTllg5HgCOvH5UFplge9S2DNeMAmRU/edit?pli=1#heading=h.agrxfsjj7zsy) for more information on PbA.
See [this doc](https://docs.google.com/document/d/1l2MfuYxqp-uycF9lVQxcPabhrQRAlmr34WnfM2YkGec/edit#heading=h.4rdqq2yi5sqg) for more information on the flow and what decisions we made.

## How
Use existing secret coordinate saving code to save our tokens and then return the secret ID to be reused at a later time/date.

## 🚨 User Impact 🚨
No user impact/breaking changes.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

source: https://github.com/airbytehq/airbyte/pull/22151

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
> @JonsSpaghetti can you help me understand how the consumer of this method will use the secretID returned? I wasn't able to follow it from [this doc](https://docs.google.com/document/d/1l2MfuYxqp-uycF9lVQxcPabhrQRAlmr34WnfM2YkGec/edit#)

The secret ID returned will be used for source/destination creation (initially just source creation). The intent is to provide the caller something that they can use to tell us what secrets to use for creating the source without us actually passing raw access/refresh tokens around.

source: https://github.com/airbytehq/airbyte/pull/22151#issuecomment-1424906220

**Comment by octavia-squidington-iii** [comment]
@davinchia I've heard through the grapevine that you're the best person to review this from the platform side. Any chance I can get you to take a look?

source: https://github.com/airbytehq/airbyte/pull/22151#issuecomment-1426439677

**Comment by octavia-squidington-iii** [comment]
@davinchia requested your re-review. After doing manual testing I feel pretty good that this is going to work for us. I added a very basic unit test to ensure that the old behavior is always the default and that we don't call the new code if the flag isn't included. I feel slightly more comfortable with this given that I don't think I changed any logic in the old flow and really only added a completely separate conditional branch to the endpoint handler.

Longer term I think we envision creating a mock authorization server so that we can do a full acceptance test which isn't feasible right now because once we need to talk to the authorization server, we can't mock interaction with the HttpClient and the auth server (rightfully) rejects us since we're using garbage credentials for the test.

If you're ok with that plus the manual testing then this is hopefully good to go, but will wait for you to 👀 

source: https://github.com/airbytehq/airbyte/pull/22151#issuecomment-1430635637

**Comment by octavia-squidington-iii** [comment]
### Airbyte Code Coverage
|File|Coverage [32.29%]|:x:|
|:-|:-:|:-:|
|[SecretsRepositoryWriter.java](https://github.com/airbytehq/airbyte/blob/e0af7377757e21f5ff0a902f729c6cd0fcecd62e/airbyte-config%2Fconfig-persistence%2Fsrc%2Fmain%2Fjava%2Fio%2Fairbyte%2Fconfig%2Fpersistence%2FSecretsRepositoryWriter.java)|83.33%|:green_apple:|
|[ServerApp.java](https://github.com/airbytehq/airbyte/blob/e0af7377757e21f5ff0a902f729c6cd0fcecd62e/airbyte-server%2Fsrc%2Fmain%2Fjava%2Fio%2Fairbyte%2Fserver%2FServerApp.java)|0%|:x:|
|[SourceOauthApiController.java](https://github.com/airbytehq/airbyte/blob/e0af7377757e21f5ff0a902f729c6cd0fcecd62e/airbyte-server%2Fsrc%2Fmain%2Fjava%2Fio%2Fairbyte%2Fserver%2Fapis%2FSourceOauthApiController.java)|0%|:x:|

|Total Project Coverage|27.23%|:green_apple:|
|:-|:-:|:-:|

source: https://github.com/airbytehq/airbyte/pull/22151#issuecomment-1433774261

**Comment by JonsSpaghetti** [comment]
@davinchia just want your re-review on this since I moved it to the new repo. I see the generated docs file maybe should be removed, can you confirm that it makes sense to remove that?

**Review by davinchia — APPROVED** [review]
@JonsSpaghetti the generated files is expected since we are changing the open api spec and so the generated documentation is changing.

Otherwise looks good!

**Comment by octavia-approvington** [comment]
Lets merge it <br/> sheep thumbs up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
