### PR TITLE
Add missing extraContainers to cron

### PR DESCRIPTION
**Pull request by nightmareartist**
Signed-off-by: Marko Milenovic <marko@mailnord.com>

## What
airbyte-cron is missing `extraContainers` from `deployment.yaml` file. The variable is in `values.yaml` but it's never used. This prevents the charts from being used in GCP with SQL proxy enabled.

## How
I've added the missing code. There is an existing PR for this issue ([#20506](https://github.com/airbytehq/airbyte/pull/20506)) but the solution in it will fail since the indentation is wrong. That PR has been inactive for a while so I'm creating a new one.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@cpdeethree can you review this community contribution?

**Comment by marcosmarxm** [comment]
@nightmareartist sorry the delay to review this!

**Review by marcosmarxm — APPROVED** [review]

**Review by cpdeethree — APPROVED** [review]
Nice work and thank you for the contribution!

**Comment by cpdeethree** [comment]
@nightmareartist this was merged and is now mainlined via https://github.com/airbytehq/airbyte-platform/commit/0598a41204ea9978e44b82778f37746486768922

**Pull request closed without merging**
