### PR TITLE
🐛  Fix parsing docker image when the full image name contains registry port

### PR DESCRIPTION
**Pull request by ogusak**
## What
The existing docker image parsing assumes only a single `:` delimiter in the image name which is used to denote image tag in the image name. However, in a general case, the full image name may contain registry host with port number, which is also delimited with `:`.
 
See full description [here](https://github.com/airbytehq/airbyte/issues/43376) 

## How
Parse full image name into version and image name based on the last occurrence of `:` delimiter

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the fix @ogusak I'm gonna ask the platform team to review this during the week.

**Comment by ogusak** [comment]
@marcosmarxm - could you check with your team please on reviewing this PR - thanks!

**Comment by ogusak** [comment]
Hi @marcosmarxm - could someone take a look at this PR. Thanks!

**Comment by marcosmarxm** [comment]
Can someone from @airbytehq/platform-compose / @airbytehq/platform-move take a look into this small contribution?

**Comment by marcosmarxm** [comment]
Sorry the delay @ogusak. @jdpgrailsdev can you help reviewing this contribution, thanks!

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by ogusak** [comment]
Thanks a lot for taking a look, @jdpgrailsdev !

**Comment by jdpgrailsdev** [comment]
@ogusak I'm not sure why the CI actions didn't catch this, but there appears to be a failing test in this PR:

```
ConnectorApmSupportHelperTest > testExtractAirbyteVersionFromBlankImageName() FAILED
    java.lang.NullPointerException: Cannot invoke "String.lastIndexOf(String)" because "image" is null
        at io.airbyte.workers.helper.ConnectorApmSupportHelper.getImageName(ConnectorApmSupportHelper.java:77)
        at io.airbyte.workers.helper.ConnectorApmSupportHelperTest.testExtractAirbyteVersionFromBlankImageName(ConnectorApmSupportHelperTest.java:49)
```

**Comment by ogusak** [comment]
@jdpgrailsdev - thanks for surfacing that error! Fixed it in the latest commit where I restored the original check for null/empty image name in `ConnectorApmSupportHelper`.

**Comment by jdpgrailsdev** [comment]
Closing, as this has been merged internally and replicated to this repository.

**Comment by jdpgrailsdev** [comment]
@ogusak Release [v0.64.7](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.64.7) contains this fix.

**Comment by ogusak** [comment]
Thank a lot, @jdpgrailsdev !

**Pull request closed without merging**
