### PR TITLE
🪟 🔧 Hide the react query devtool button in cypress

### PR DESCRIPTION
**Pull request by timroes**
Migration of https://github.com/airbytehq/airbyte/pull/23078

## What

Hides the react query devtools button while running in cypress. When developing locally you usually have a dev version running that you run cypress tests against (via `cypress:open`), which has that button visible by default. We've seen cases where the button overlaps another button and cypress can't click that unerlying button in this case. So making sure we always hide that button when running cypress cases.

### CODE REVIEW

**Review by octavia-squidington-iii — APPROVED** [review]
A bit boring PR, but I'll nevertheless approve it, since Alex and Teal already approved the original PR.

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Comment by timroes** [comment]
Conflicts resolved.

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
