### PR TITLE
Add ingress object for exposing airbyte-api-server

### PR DESCRIPTION
**Pull request by larrywax**
## What
This PR adds an ingress object to the airbyte-api-server chart in order to expose the API outside of the kubernetes cluster

## How
Add helm template for ingress object

## Can this PR be safely reverted / rolled back?
- [x] YES 💚
- [ ] NO ❌

## 🚨 User Impact 🚨
If the user enables and configures the ingress, an ingress object will be created

### CODE REVIEW

**Comment by larrywax** [comment]
Can someone have a look a this PR? 🙏 
We had to fork the official helm chart because we really need to expose Airbyte APIs outside of our k8s cluster, but I would love to switch back to the official one as soon as possible

**Comment by oleksandr-gubchenko** [comment]
any updates?

**Comment by damjantrickovik-hofy** [comment]
> Author

Are you using the OSS version of Airbyte?

**Comment by larrywax** [comment]
> [larrywax](https://github.com/larrywax) Are you using the OSS version of Airbyte?

Yes, we do, but we plan to move to enterprise at some point

**Review by cpdeethree — APPROVED** [review]
Thanks for the contribution!

**Comment by cpdeethree** [comment]
This was merged and released as part of https://github.com/airbytehq/airbyte-platform/commit/73eaf48d73764fecaa2f91f6c4304a4a55122bc3

Thanks for your contribution!

**Pull request closed without merging**
